/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.CI;

import DB.CI.BillImpleCrud;
import DB.CI.MaterialImpleCrud;
import DB.CI.SupplierImpleCrud;
import Clases.Bill;
import Clases.Material;
import Clases.PurchaseDetails;
import Clases.Supplier;
import Restriciones.Habilitadores;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import Interfaces.ICrudGeneric;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class FormPurchase extends javax.swing.JFrame {

    /**
     * Creates new form frmVenta
     */
    private TextAutoCompleter txtAutoProveedor;
    private ICrudGeneric crud;
    private Habilitadores habilitador;
    private ArrayList<Supplier>alSupplier;
    private Supplier supplier;
    private FormAddMaterial formAddMaterial;
    private FormAddSupplier formAddSupplier;
    private FormSearchSupplier formSearchSupplier;
    private FormSupplier formSupplier;
    private SimpleDateFormat fecha;
    public Bill bill;
    public DefaultTableModel modelo;
    private ArrayList<Material>almaterial;
    private ArrayList<PurchaseDetails> purchaseDetails;
    public FormPurchase() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.alSupplier = new ArrayList<>();
        this.habilitador = new Habilitadores();
        this.almaterial = new ArrayList<>();
        this.bill = new Bill();
        this.purchaseDetails = new ArrayList<>();
        this.fecha = new SimpleDateFormat("dd-mm-YYYY");
        this.habilitador.cambiarEstadoComponentes(this.panelProducto.getComponents(), false);
        this.habilitador.cambiarEstadoComponentes(this.panelObservaciones.getComponents(), false);
        this.habilitador.cambiarEstadoComponentes(this.panelPago.getComponents(), false);
        this.habilitador.cambiarEstadoComponentes(this.panelBotonera.getComponents(), false);
        this.lbFecha.setText(fecha.format(new Date()));
        this.modelo = (DefaultTableModel) this.tablaDetalleCompra.getModel();
        this.lbNCompra.setText(String.valueOf(new BillImpleCrud().ultimo()));
        inicializador();
    }
    
    private void inicializador(){
        txtAutoProveedor = new TextAutoCompleter(txtNombreProveedor);
        crud = new SupplierImpleCrud();
        alSupplier = crud.obtener();
        alSupplier.forEach((lista)->{
            txtAutoProveedor.addItem(lista.getCompany_name());
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFactura = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNCompra = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        panelProveedor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBusquedaAvanzada = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtNombreProveedor = new javax.swing.JTextField();
        btnRegistarProveedor = new javax.swing.JButton();
        panelProducto = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnConsultarDisponibilidad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleCompra = new javax.swing.JTable();
        btnAgregarMaterial = new javax.swing.JButton();
        panelObservaciones = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtIVA = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panelPago = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtMora = new javax.swing.JTextField();
        txtPlazos = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panelBotonera = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Panel Compra");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("N° de Compra:");

        jLabel3.setText("Fecha De Compra:");

        lbNCompra.setText("151565-56-655");

        lbFecha.setText("28 de septiembre 2019");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbFecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbNCompra))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbFecha))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelFactura.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 11, 290, 90));

        panelProveedor.setBackground(new java.awt.Color(255, 255, 255));
        panelProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Proveedor:");
        panelProveedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 20, -1, -1));

        btnBusquedaAvanzada.setText("Búsqueda Avanzada");
        btnBusquedaAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaAvanzadaActionPerformed(evt);
            }
        });
        panelProveedor.add(btnBusquedaAvanzada, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 45, -1, -1));

        btnAgregar.setText("Agregar a factura");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelProveedor.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 16, -1, -1));

        txtNombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProveedorKeyTyped(evt);
            }
        });
        panelProveedor.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 17, 314, -1));

        btnRegistarProveedor.setText("Ver Proveedores");
        btnRegistarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarProveedorActionPerformed(evt);
            }
        });
        panelProveedor.add(btnRegistarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 45, -1, -1));

        panelFactura.add(panelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, 598, 80));

        panelProducto.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("PRODUCTO:");

        btnConsultarDisponibilidad.setText("Quitar Producto");
        btnConsultarDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDisponibilidadActionPerformed(evt);
            }
        });

        tablaDetalleCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de material", "Precio Unitario", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDetalleCompra.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tablaDetalleCompra);
        if (tablaDetalleCompra.getColumnModel().getColumnCount() > 0) {
            tablaDetalleCompra.getColumnModel().getColumn(0).setPreferredWidth(450);
            tablaDetalleCompra.getColumnModel().getColumn(1).setPreferredWidth(80);
            tablaDetalleCompra.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        btnAgregarMaterial.setText("Agregar Material");
        btnAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarMaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultarDisponibilidad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnConsultarDisponibilidad)
                    .addComponent(btnAgregarMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelFactura.add(panelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 598, 190));

        panelObservaciones.setBackground(new java.awt.Color(255, 255, 255));
        panelObservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("SubTotal");

        jLabel9.setText("IVA");

        jLabel10.setText("Total");

        jLabel11.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        javax.swing.GroupLayout panelObservacionesLayout = new javax.swing.GroupLayout(panelObservaciones);
        panelObservaciones.setLayout(panelObservacionesLayout);
        panelObservacionesLayout.setHorizontalGroup(
            panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelObservacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelObservacionesLayout.setVerticalGroup(
            panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObservacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelObservacionesLayout.createSequentialGroup()
                        .addGroup(panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelObservacionesLayout.createSequentialGroup()
                                .addGroup(panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25))
                            .addGroup(panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGap(3, 3, 3)
                        .addGroup(panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFactura.add(panelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 598, -1));

        jPanel5.setBackground(new java.awt.Color(33, 89, 103));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Panel de Compra");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFactura.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 302, 90));

        panelPago.setBackground(new java.awt.Color(255, 255, 255));
        panelPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setText("Mora:");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setText("Plazos:");

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setText("Dias:");

        jPanel8.setBackground(new java.awt.Color(33, 89, 103));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Plan de pago");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel18)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout panelPagoLayout = new javax.swing.GroupLayout(panelPago);
        panelPago.setLayout(panelPagoLayout);
        panelPagoLayout.setHorizontalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMora, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlazos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panelPagoLayout.setVerticalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        panelFactura.add(panelPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 598, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Restablecer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoneraLayout = new javax.swing.GroupLayout(panelBotonera);
        panelBotonera.setLayout(panelBotoneraLayout);
        panelBotoneraLayout.setHorizontalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        panelBotoneraLayout.setVerticalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoneraLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(jButton2))
                .addGap(10, 10, 10))
        );

        panelFactura.add(panelBotonera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 598, 42));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMaterialActionPerformed
        // TODO add your handling code here:
        if (formAddMaterial == null) {
            formAddMaterial = new FormAddMaterial(this,supplier);
            formAddMaterial.setVisible(true);
        }else{
            formAddMaterial.setVisible(true);
        }
    }//GEN-LAST:event_btnAgregarMaterialActionPerformed

    private void btnRegistarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarProveedorActionPerformed
        // TODO add your handling code here:
        if (formSupplier == null) {
            formSupplier = new FormSupplier(this);
            formSupplier.setVisible(true);
        }else{
            formSupplier.setVisible(true);
        }
    }//GEN-LAST:event_btnRegistarProveedorActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try
        {
            BillImpleCrud billImpleCrud = new BillImpleCrud();
            this.bill.setAlMaterial(almaterial);
            this.bill.setIva(Float.parseFloat(this.txtIVA.getText()));
            this.bill.setObservations(this.txtObservaciones.getText());
            this.bill.setPurchase_date(new java.sql.Date(new Date().getTime()));
            this.bill.setPurchase_id(0);
            this.bill.setPurchase_status(0);
            this.bill.setSubtotal(Float.parseFloat(this.txtSubTotal.getText()));
            this.bill.setSupplier(supplier);
            this.bill.setTotal(Float.parseFloat(this.txtTotal.getText()));
            billImpleCrud.sebastian(billImpleCrud.ultimo(), bill.getTotal(), Integer.parseInt(txtPlazos.getText()),Float.parseFloat(txtMora.getText()),
                    this.bill.getPurchase_date());
            if (billImpleCrud.ingresar(bill)) {
                JOptionPane.showMessageDialog(null, "¡Exito en la operacion!","Mensaje de Sistema",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "¡Error en uno o más campos!","Mensaje de Sistema",JOptionPane.ERROR_MESSAGE);
            }
            this.lbNCompra.setText(String.valueOf(new BillImpleCrud().ultimo()));
        }catch(NumberFormatException ex){
            
            JOptionPane.showMessageDialog(null, "¡Error en uno o más campos!","Mensaje de Sistema",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProveedorKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreProveedorKeyReleased

    private void txtNombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProveedorKeyTyped
        // TODO add your handling code here:
//        ValidacionKeyTyped vt = new ValidacionKeyTyped();
//        vt.validacionNumeroReal(evt, txtNombreProveedor, 2);
    }//GEN-LAST:event_txtNombreProveedorKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        this.busqueda(this.txtNombreProveedor.getText().trim());
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        almaterial.removeAll(almaterial);
        this.modelo.setRowCount(0);
        txtSubTotal.setText(null);
        txtTotal.setText(null);
        txtDias.setText(null);
        txtMora.setText(null);
        txtPlazos.setText(null);
        this.habilitador.cambiarEstadoComponentes(this.panelProducto.getComponents(), false);
        this.habilitador.cambiarEstadoComponentes(this.panelObservaciones.getComponents(), false);
        this.habilitador.cambiarEstadoComponentes(this.panelPago.getComponents(), false);
        this.habilitador.cambiarEstadoComponentes(this.panelBotonera.getComponents(), false);
        this.habilitador.cambiarEstadoComponentes(this.panelProveedor.getComponents(), true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBusquedaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaAvanzadaActionPerformed
        // TODO add your handling code here:
        if (formSearchSupplier==null) {
            FormSearchSupplier formSearchSupplier = new FormSearchSupplier(this);
            formSearchSupplier.setVisible(true);
        }else{
            formSearchSupplier.setVisible(true);
        }
    }//GEN-LAST:event_btnBusquedaAvanzadaActionPerformed

    private void btnConsultarDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDisponibilidadActionPerformed
        // TODO add your handling code here:
        double subtotal=0;
        if (!almaterial.isEmpty()) {
            String valor = this.tablaDetalleCompra.getValueAt(this.tablaDetalleCompra.getSelectedRow(), 0).toString();
            almaterial.removeIf(lista -> lista.getMaterial_name().equals(valor));
            this.modelo.setRowCount(0);
        for (Material material1 : almaterial) {
                this.modelo.addRow(new Object[]{
                material1.getMaterial_name(),material1.getUnit_price(),material1.getUnits_in_stock()
            });
            subtotal+= material1.getUnit_price()*material1.getUnits_in_stock();
        }
            txtSubTotal.setText(String.valueOf(subtotal));
            txtTotal.setText(String.valueOf(subtotal*1.13));
        }
        if (almaterial.isEmpty()) {
                txtSubTotal.setText(null);
                txtTotal.setText(null);
                this.habilitador.cambiarEstadoComponentes(this.panelBotonera.getComponents(), false);
        }
    }//GEN-LAST:event_btnConsultarDisponibilidadActionPerformed

    public void busqueda(Supplier psupplier){
        for (Supplier supplier : alSupplier) {
            if (supplier.getCompany_name().equals(psupplier.getCompany_name())) {
                this.supplier = new Supplier();
                this.supplier = supplier;
                this.habilitador.cambiarEstadoComponentes(this.panelProducto.getComponents(), true);
                this.habilitador.cambiarEstadoComponentes(this.panelPago.getComponents(), true);
                this.habilitador.cambiarEstadoComponentes(this.panelBotonera.getComponents(), true);
                this.habilitador.cambiarEstadoComponentes(this.panelProveedor.getComponents(), false);
                this.txtNombreProveedor.setText(psupplier.getCompany_name());
                JOptionPane.showMessageDialog(null, "¡Agregado con éxito!","Mensaje de Sistema",JOptionPane.INFORMATION_MESSAGE);
                break;
            }
        }
    }
    public void busqueda(String psupplier){
        for (Supplier supplier : alSupplier) {
            if (supplier.getCompany_name().equals(psupplier)) {
                this.supplier = new Supplier();
                this.supplier = supplier;
                this.habilitador.cambiarEstadoComponentes(this.panelProducto.getComponents(), true);
                this.habilitador.cambiarEstadoComponentes(this.panelPago.getComponents(), true);
                this.habilitador.cambiarEstadoComponentes(this.panelProveedor.getComponents(), false);
                this.txtNombreProveedor.setText(psupplier);
                JOptionPane.showMessageDialog(null, "¡Agregado con éxito!","Mensaje de Sistema",JOptionPane.INFORMATION_MESSAGE);
                break;
            }
        }
    }
    public void agregarMaterial(Material material){
        boolean con=false;    
        double subtotal=0;
        for (Material material1 : almaterial) {
            if (material1.getMaterial_name().equals(material.getMaterial_name())) {
                material1.setUnits_in_stock(material1.getUnits_in_stock()+material.getUnits_in_stock());
                con = true;
                break;
            }
        }
        if (con==false) {
            this.almaterial.add(material);
            this.modelo.addRow(new Object[]{
                material.getMaterial_name(),material.getUnit_price(),material.getUnits_in_stock()
            });
        }else{
            this.modelo.setRowCount(0);
            for (Material material1 : almaterial) {
                this.modelo.addRow(new Object[]{
                material1.getMaterial_name(),material1.getUnit_price(),material1.getUnits_in_stock()
            });
            }
        }
        for (Material material1 : almaterial) {
            subtotal+= material1.getUnit_price()*material1.getUnits_in_stock();
        }
        txtSubTotal.setText(String.valueOf(subtotal));
        txtTotal.setText(String.valueOf(subtotal*1.13));
        this.habilitador.cambiarEstadoComponentes(this.panelBotonera.getComponents(), true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPurchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarMaterial;
    private javax.swing.JButton btnBusquedaAvanzada;
    private javax.swing.JButton btnConsultarDisponibilidad;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegistarProveedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbNCompra;
    private javax.swing.JPanel panelBotonera;
    private javax.swing.JPanel panelFactura;
    private javax.swing.JPanel panelObservaciones;
    private javax.swing.JPanel panelPago;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JPanel panelProveedor;
    public javax.swing.JTable tablaDetalleCompra;
    private javax.swing.JTextField txtDias;
    public javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtMora;
    public javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPlazos;
    public javax.swing.JTextField txtSubTotal;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
