/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.CI;

import DB.CI.SupplierImpleCrud;
import Clases.Supplier;
import javax.swing.JOptionPane;
import Interfaces.ICrudGeneric;
import Restriciones.Borrar;
import Restriciones.ValidacionKeyRealeased;
import Restriciones.ValidacionKeyTyped;
import javax.swing.JTextField;

/**
 *
 * @author Alejandro
 */
public class FormAddSupplier extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregarCliente
     */
    private FormSupplier formSupplier;
    private Borrar borrar;
    private ValidacionKeyRealeased validacionKeyRealeased;
    private ValidacionKeyTyped ValidacionKeyTyped;
    public FormAddSupplier(FormSupplier formSupplier) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.formSupplier = formSupplier;
        this.validacionKeyRealeased = new ValidacionKeyRealeased();
        this.ValidacionKeyTyped = new ValidacionKeyTyped();
        borrar = new Borrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTituloContacto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombreContacto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtNrc = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Proveedor");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel29.setBackground(new java.awt.Color(33, 89, 103));
        jPanel29.setPreferredSize(new java.awt.Dimension(682, 60));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Agregar Proveedor");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel24)
                .addGap(15, 15, 15))
        );

        btnAgregarCliente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(550, 10));
        jPanel4.setLayout(new java.awt.GridLayout(7, 2, 14, 14));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setText("Nombre Proveedor:");
        jPanel4.add(jLabel22);

        txtNombreProveedor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProveedorKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombreProveedor);

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setText("Título de contacto:");
        jPanel4.add(jLabel13);

        txtTituloContacto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTituloContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTituloContactoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloContactoKeyTyped(evt);
            }
        });
        jPanel4.add(txtTituloContacto);

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setText("Ciudad:");
        jPanel4.add(jLabel15);

        txtCiudad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCiudadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiudadKeyTyped(evt);
            }
        });
        jPanel4.add(txtCiudad);

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setText("Código postal:");
        jPanel4.add(jLabel17);

        txtCodigoPostal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCodigoPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoPostalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoPostalKeyTyped(evt);
            }
        });
        jPanel4.add(txtCodigoPostal);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel19.setText("Teléfono:");
        jPanel4.add(jLabel19);

        txtTelefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel4.add(txtTelefono);

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("Email:");
        jPanel4.add(jLabel21);

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jPanel4.add(txtEmail);

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("Nombre de contacto:");
        jPanel4.add(jLabel12);

        txtNombreContacto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNombreContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreContactoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreContactoKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombreContacto);

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setText("Direcciòn:");
        jPanel4.add(jLabel14);

        txtDireccion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel4.add(txtDireccion);

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setText("Regiòn:");
        jPanel4.add(jLabel16);

        txtRegion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtRegion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRegionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegionKeyTyped(evt);
            }
        });
        jPanel4.add(txtRegion);

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel18.setText("Paìs:");
        jPanel4.add(jLabel18);

        txtPais.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel4.add(txtPais);

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setText("Fax:");
        jPanel4.add(jLabel20);

        txtFax.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFaxKeyTyped(evt);
            }
        });
        jPanel4.add(txtFax);

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel23.setText("Nrc:");
        jPanel4.add(jLabel23);

        txtNrc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNrc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNrcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNrcKeyTyped(evt);
            }
        });
        jPanel4.add(txtNrc);

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel25.setText("Nit:");
        jPanel4.add(jLabel25);

        txtNit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNitKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNitKeyTyped(evt);
            }
        });
        jPanel4.add(txtNit);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnAgregarCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(btnAgregarCliente)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        Supplier supplier = new Supplier(0, this.txtNombreProveedor.getText().trim(), this.txtNombreContacto.getText().trim(),
                this.txtTituloContacto.getText().trim(), this.txtDireccion.getText().trim(), this.txtEmail.getText().trim(),
                this.txtCiudad.getText().trim(), this.txtRegion.getText(), this.txtCodigoPostal.getText().trim(),
                this.txtPais.getText().trim(), this.txtTelefono.getText(), this.txtFax.getText(), this.txtNrc.getText().trim(),
                this.txtNit.getText().trim());
        ICrudGeneric crud = new SupplierImpleCrud();
        if (crud.ingresar(supplier)) {
            JOptionPane.showMessageDialog(null, "¡Agregado con éxito!","Mensaje de Sistema",JOptionPane.INFORMATION_MESSAGE);
            this.formSupplier.inicializar();
            this.borrar.borrar(new JTextField[]{this.txtCiudad,this.txtCodigoPostal,this.txtDireccion,this.txtEmail,
                this.txtFax,this.txtNit,this.txtNombreContacto,this.txtNombreProveedor,this.txtNrc,this.txtPais,
                this.txtRegion,this.txtTelefono,this.txtTituloContacto
            });
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "¡Ocurrio un error al ingresar el cliente!","Mensaje de Sistema",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void txtNombreProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorKeyReleased

    private void txtNombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorKeyTyped

    private void txtCiudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadKeyReleased

    private void txtCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadKeyTyped

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreContactoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreContactoKeyReleased

    private void txtNombreContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreContactoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreContactoKeyTyped

    private void txtRegionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegionKeyReleased

    private void txtRegionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegionKeyTyped

    private void txtFaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxKeyReleased

    private void txtFaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxKeyTyped

    private void txtNitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNitKeyReleased

    private void txtNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyTyped
        // TODO add your handling code here:
        this.ValidacionKeyTyped.validacionNumeroEntero(evt);
    }//GEN-LAST:event_txtNitKeyTyped

    private void txtTituloContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloContactoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloContactoKeyReleased

    private void txtTituloContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloContactoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloContactoKeyTyped

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtCodigoPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPostalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPostalKeyReleased

    private void txtCodigoPostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPostalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPostalKeyTyped

    private void txtNrcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNrcKeyTyped
        // TODO add your handling code here:
        this.ValidacionKeyTyped.validacionNumeroEntero(evt);
    }//GEN-LAST:event_txtNrcKeyTyped

    private void txtNrcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNrcKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombreContacto;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtNrc;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTituloContacto;
    // End of variables declaration//GEN-END:variables
}
