/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulo_ci;

/**
 *
 * @author chris
 */
public class frmBucarProveedor extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregarCliente
     */
    public frmBucarProveedor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtEmail19 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEmail12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmail14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtEmail16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtEmail18 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmail11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEmail13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtEmail15 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtEmail17 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Proveedor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel29.setBackground(new java.awt.Color(33, 89, 103));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Buscar Proveedor");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel24)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros de búsqueda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(550, 10));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 14, 14));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setText("Nombre Proveedor:");
        jPanel4.add(jLabel22);

        txtEmail19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail19ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail19);

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setText("Título de contacto:");
        jPanel4.add(jLabel13);

        txtEmail10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail10ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail10);

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setText("Ciudad:");
        jPanel4.add(jLabel15);

        txtEmail12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail12ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail12);

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setText("Código postal:");
        jPanel4.add(jLabel17);

        txtEmail14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail14ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail14);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel19.setText("Teléfono:");
        jPanel4.add(jLabel19);

        txtEmail16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail16ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail16);

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("Email:");
        jPanel4.add(jLabel21);

        txtEmail18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail18ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail18);

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("Nombre de contacto:");
        jPanel4.add(jLabel12);

        txtEmail9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail9ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail9);

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setText("Direcciòn:");
        jPanel4.add(jLabel14);

        txtEmail11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail11ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail11);

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setText("Regiòn:");
        jPanel4.add(jLabel16);

        txtEmail13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail13ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail13);

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel18.setText("Paìs:");
        jPanel4.add(jLabel18);

        txtEmail15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail15ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail15);

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setText("Fax:");
        jPanel4.add(jLabel20);

        txtEmail17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail17ActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail17);

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton2.setText("Buscar");

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton3.setText("Regresar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado de búsqueda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14))); // NOI18N

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Distribuidora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton1.setText("Agregar a Factura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmail19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail19ActionPerformed

    private void txtEmail10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail10ActionPerformed

    private void txtEmail12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail12ActionPerformed

    private void txtEmail14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail14ActionPerformed

    private void txtEmail16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail16ActionPerformed

    private void txtEmail18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail18ActionPerformed

    private void txtEmail9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail9ActionPerformed

    private void txtEmail11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail11ActionPerformed

    private void txtEmail13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail13ActionPerformed

    private void txtEmail15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail15ActionPerformed

    private void txtEmail17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBucarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBucarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBucarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBucarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBucarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmail10;
    private javax.swing.JTextField txtEmail11;
    private javax.swing.JTextField txtEmail12;
    private javax.swing.JTextField txtEmail13;
    private javax.swing.JTextField txtEmail14;
    private javax.swing.JTextField txtEmail15;
    private javax.swing.JTextField txtEmail16;
    private javax.swing.JTextField txtEmail17;
    private javax.swing.JTextField txtEmail18;
    private javax.swing.JTextField txtEmail19;
    private javax.swing.JTextField txtEmail9;
    // End of variables declaration//GEN-END:variables
}
